name: 'Continuous Integrations'

on:
  push:
    branches: ['main']

jobs:
  test:
    name: 'Execute unit & integration tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v3'

      - name: 'Install pnpm'
        run: 'curl -fsSL https://get.pnpm.io/install.sh | sh -'

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '16.x'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: 'Install dependencies'
        run: 'pnpm install --frozen-lockfile'

      - name: 'Execute the test script'
        run: 'pnpm run test'
